### ISSUE TITLE
As a user, I want to be able to log in so I can access all features of the website.

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/TestRepository#1]
### Task list - Login (S1)

- [ ] User can enter their credentials (username & password) in appropriately labelled fields.
- [ ] A login button only becomes clickable if the credential fields contain valid input.
- [ ] Upon successful login, the user is redirected to the main menu.
- [ ] Upon unsuccessful login, the user is notified with an appropriate error message and the credential fields are cleared.
- [ ] A logged-in user who tries to navigate to the login screen manually is redirected to the main menu.
